updated readme

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,10 +1,6 @@
 #!/bin/bash
 # -*- coding: utf-8 -*-
 echo "==>  gathering system facts"
-# operating system
-#   Darwin = OSX
-#   Linux  = Linux
-#   <>     = Windows
 echo "OS: " `uname`
 echo "HOSTNAME: " `hostname`
 echo "USER: " `whoami`
@@ -12,22 +8,18 @@ echo "PWD: " `pwd`
 
 
 echo "==>  copying program files"
-# copy bin/whomst to /usr/bin
 sudo cp ./whomst/__init__.py /usr/local/bin/whomst
-# ensure that whomst still has exec tag
 ls -la /usr/local/bin/whomst
 
 
 echo "==>  test installation"
 cd ./tests
-whomst .
-
-# x=`whomst | grep foo`
-# # echo "x=$x"
-# [ "$x" == "foo" ] && echo "ok" || echo "invalid"
-# y=`whomst | grep bar`
-# # echo "y=$y"
-# [ "$y" == "bar" ] && echo "ok" || echo "invalid"
-# z=`whomst | grep new`
-# # echo "z=$z"
-# [ "$z" == "new" ] && echo "ok" || echo "invalid"
+x=`whomst . | grep foo`
+# echo "x=$x"
+[ "$x" == "foo" ] && echo "ok" || echo "invalid"
+y=`whomst . | grep bar`
+# echo "y=$y"
+[ "$y" == "bar" ] && echo "ok" || echo "invalid"
+z=`whomst . | grep new`
+# echo "z=$z"
+[ "$z" == "new" ] && echo "ok" || echo "invalid"
